### ISSUE TITLE
Data layers - Expose HVRA dataset from backend

### ISSUE THREAD

**Issue by elsiel23** [OurPlanscape/Planscape#103]

**Comment by mskim3494** [comment]
Layers that need to be added to the DB and made available, scope for this issue

- Roads -- Laurens can provide the road layer for all of California
- Slope -- fiind [here](https://app.box.com/s/8ehz2mtmzabai5fs4cwj7ot2loz9jgot)
- Buildings -- will be made available with https://github.com/OurPlanscape/Planscape/issues/277
- Fire History -- Download [here](https://frap.fire.ca.gov/media/ly2jyr4j/fire21_2.zip)

**Comment by elsiel23** [comment]
Is this still blocked? When do we want this by?

**Comment by mskim3494** [comment]
New bugs have been created or repurpose to replace this one.
Fire History https://github.com/OurPlanscape/Planscape/issues/447
Buildings https://github.com/OurPlanscape/Planscape/issues/277
Road and slope https://github.com/OurPlanscape/Planscape/issues/276
