### ISSUE TITLE
Update sidebar UI to match mocks

### ISSUE THREAD

**Issue by lattemilk** [OurPlanscape/Planscape#118]
Also need to figure out the expected behavior when the sidebar is toggled (i.e. does the entire map shift? or just shift the left panel while the map stays static?)

**Comment by ayee07** [comment]
![Image](https://user-images.githubusercontent.com/101600975/207167994-2b184d0d-4b52-4aba-a2e0-9703608bc9c3.png)

The sidebar will slide out from left to right and shift the map and map layer panel over. (How it's currently implemented)

**Behavior:**
If user is not signed in/has no account, the sidebar has the following:
Dashboard
Map
Configuration
-----
My Plans
> Create new plan (if they click on this, then prompt sign in)

If they are an existing user and are signed in, the sidebar has the following:
Dashboard
Map
Configuration
------
My Plans
> Plan 1 name
> Plan 2 name
> Plan 3 name (up to three most recent plans user has modified)
> Create new plan

State of each slice:
Highlight the active slice (for example, I'm looking at the Map, then click the sidebar icon. The "Map" item should be highlighted in list.

Only one item can be highlighted at a time.

Lmk if you need any more details!
