### ISSUE TITLE
Make it easy to incorporate a new boundary layer in the frontend 

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#134]
It should be easier to incorporate a new boundary layer than what has been done with Pull Requests like https://github.com/OurPlanscape/Planscape/pull/128.  Ideally, the frontend should be able to query the list of boundary layers through “GET /boundary/boundary/” and populate the checkboxes from that.

**Comment by riecke** [comment]
I think GET /boundary/boundary/ works now:

 wget -O /tmp/foo "http://127.0.0.1:8000/boundary/boundary"

Output looks like

  [{"id":20,"boundary_name":"california_counties"},{"id":30,"boundary_name":"tcsi_huc12"},{"id":31,"boundary_name":"tcsi_fire_perimeters"},{"id":32,"boundary_name":"task_force_regions"},{"id":33,"boundary_name":"counties"},{"id":34,"boundary_name":"huc12"},{"id":35,"boundary_name":"huc10"},{"id":36,"boundary_name":"USFS"}]

**Comment by thequeenofspades** [comment]
Got it, I'll work on it. Can you add display names to the boundary output?

**Comment by riecke** [comment]
Added!  See https://github.com/OurPlanscape/Planscape/pull/178, and thanks for the review.
