### ISSUE TITLE
Add help info to the bar with create plan options

### ISSUE THREAD

**Issue by lattemilk** [OurPlanscape/Planscape#140]
The bar below top-bar.
For example, it should say "you are drawing a planning area" when the drawing tool is activated.

**Comment by lattemilk** [comment]
This is P1 based on prioritization discussions

**Comment by lattemilk** [comment]
oo there's a Priority attribute for github issues. I set it to Medium

**Comment by runforyourlives** [comment]
Closed/obsolete, as the UI has changed significantly.  There is an overarching expectation to provide help/tooltips all throughout the tool.
