### ISSUE TITLE
[Multimap view] Save user's multimap settings in local storage

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#152]
We want to save the user's multimap settings (how many maps were visible, which map was selected, what the map configs were) in local storage. Later, when we have session/user database schemas, we can move this data out of local storage and into the backend.

**Comment by thequeenofspades** [comment]
Open question: how often do we want to save this data? Every time the user changes a map (e.g. toggles a layer on/off), every X amount of time, or only when the page is destroyed?

**Comment by ayee07** [comment]
I like the "Saving every X amount of time" option. Seems like a good middle-ground.

**Comment by thequeenofspades** [comment]
OK! How does every 60 seconds sound? We could probably bundle this in with a future autosave feature when the user starts working on plans.
