### ISSUE TITLE
Indicate one of four California regions

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#18]
Indicate which of the four region the user is a part of
MVP is Sierra Nevada only
Other regions are “coming”, gray out unavailable regions
Allow users to create plans across regions separately in each region

**Comment by lattemilk** [comment]
Questions:
1. Are there boundaries or central coordinates to focus on in the map for each region?
2. What zoom default zoom level?
3. Upon clicking on a region --> goes to explore tab and the location on the map?

**Comment by riecke** [comment]
What's the best way to give you the boundaries?

- Would a jpg or gif file be best? 
- Should it be 1 file or 4 files for the four regions?
 
The regions don't need to be populated with heatmaps or data---just some indication of whether the data is available or not (e.g., gray-out the regions for which we have no data yet)

**Comment by riecke** [comment]
To answer the other questions:

2. No zoom level for this region-selection page.  No zoom is needed.
3. Upon clicking on a region, yes, should go to the explore tab and maybe the center point of the region when displayed in Leaflet.

**Comment by lattemilk** [comment]
Thanks for answering the questions :)
I was thinking I needed to define the selected region area in the explore map and gray out the rest of the map. I'd probably need geojson? What did you have in mind?

**Comment by lattemilk** [comment]
Found this https://gis.data.cnra.ca.gov/datasets/727b3cc24f8549759fe946a298dc3a20_0/explore?location=38.469117%2C-120.319169%2C7.26
