### ISSUE TITLE
Error enforcing max extent constraint in conditions_conditionraster table

### ISSUE THREAD

**Issue by elsiel23** [OurPlanscape/Planscape#181]
Running the raster2pgsql script to load element rasters raises the error:

Processing 1/1: /Users/elsieling/cnra/env/data/sierra_nevada/biodiversity/focal_species/CA_Black_Oak_Stand_Distribution_2016to2020_300m.tif
BEGIN
ERROR:  new row for relation "conditions_conditionraster" violates check constraint "enforce_max_extent_raster"
DETAIL:  Failing row contains (386, 01000001000000000000C072400000000000C072C044BCEEE7510440C180B89F..., CA_Black_Oak_Stand_Distribution_2016to2020_300m.tif).
CONTEXT:  COPY conditions_conditionraster, line 1: "01000001000000000000C072400000000000C072C044BCEEE7510440C180B89FEACF5B424100000000000000000000000000..."
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK

`select ST_EXTENT(extent) from raster_columns where r_table_name='conditions_conditionraster'` gives me
BOX(-2228663.8119731266 1546203.832999289,-1844663.8119731266 2391003.832999289) as (xmin, ymin, xmax, ymax)

whereas the RRK has
BoundingBox(left=-2535863.8119731266, bottom=1419303.832999289, right=-1553663.8119731266, top=2544603.832999289)

**Comment by runforyourlives** [comment]
Closed/obsolete.
