### ISSUE TITLE
[Create a plan] Upload a shape (frontend)

### ISSUE THREAD

**Issue by lattemilk** [OurPlanscape/Planscape#193]
- Create a file uploader component
- Handle upload, cancel, validation, etc
- Convert to geojson and add to the map

**Comment by riecke** [comment]
Is this the same as #25 ?

I've done some investigation, and this article gives a good description: https://hub.packtpub.com/shapefiles-leaflet/

The two libraries are

- https://github.com/calvinmetcalf/leaflet.shapefile (not very active, but not much code either)
- https://github.com/calvinmetcalf/shapefile-js (main conversion from shapefiles to GeoJSON, active)
