### ISSUE TITLE
Map layer panel- add info button, hover state behavior, and callout function

### ISSUE THREAD

**Issue by ayee07** [OurPlanscape/Planscape#195]
Users may not know what the Pillars and Elements are. We need to provide easy access to definitions and source references from the map layer panel (specifically the stuff in the ecosystem score).
See mockup:
<img width="1252" alt="Screen Shot 2022-12-06 at 4 20 27 PM" src="https://user-images.githubusercontent.com/101600975/206055412-491e1e09-c9ce-4423-bed4-a53b7a88b9f5.png">

**Comment by thequeenofspades** [comment]
The Angular Material component library doesn't include a popover/callout component, so getting a callout to look exactly as it does in the screenshot above will require creating a custom component. Here's what I can do without creating a custom component and reusing the existing menu component:

![image](https://user-images.githubusercontent.com/10444733/206284531-8f9e457b-ac50-46b4-b2ac-7613fe5e0a16.png)

Differences:
* The positioning is different; it depends on the location of the triggering element (the info icon) and there is very little flexibility to customize positioning.
* There is no little triangle pointing to the triggering element.
* There is no button to close the menu (clicking outside of the menu closes it).

I can make the background blue and text white or whatever colors we want, I just didn't take the time to do so with this quick demo.

WDYT? Creating a custom popover component is possible, but would take several days of work (my estimate) away from other items.
