### ISSUE TITLE
Create progress bar dialog when running forsys

### ISSUE THREAD

**Issue by lattemilk** [OurPlanscape/Planscape#203]
https://material.angular.io/components/progress-bar/overview

**Comment by JanLauGe** [comment]
A `determinate` progress bar will be difficult to do. We could try to estimate total run time using variables such as size of project area, number of scenarios, etc, but it will be order of magnitude only.

**Comment by thequeenofspades** [comment]
Instead of a progress bar, latest decision is to redirect the user to the plan summary page to check the progress of their scenarios.
