### ISSUE TITLE
Backend: Save priorities and constraints for Projects

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#217]
In the diagnostic phase, a user can select priorities (elements/pillars) and set constraints.  These should be saved to a new "Project Area" object before sending to ForSys with Patchmax.  The results of the ForSys run (namely project area polygons) will be saved to the same object.

This requires an API in the Django "plan" application.

**Comment by riecke** [comment]
There is a rudimentary API now called "/planscape-backend/plan/create_project".

Keeping this open until we have more constraints and priorities to save.

**Comment by elsiel23** [comment]
Updated our API [documentation](https://cawater.sharepoint.com/:w:/r/teams/CNRA_WFRPST/_layouts/15/doc2.aspx?sourcedoc=%7B15688A15-E5ED-4462-9F99-2CD17FB3FFF1%7D&file=Planscape%20-%20Backend%20API.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1672785426609&wdOrigin=OFFICECOM-WEB.START.REC&cid=8e91df8c-3dd9-4751-a4b1-1d374be0fe24) with the project and project area endpoints

**Comment by thequeenofspades** [comment]
It should be possible to update priorities and constraints for an existing project rather than only when creating a new project. Use case: the user pauses midway through the project creation flow, before running Forsys, and resumes planning at a later time.

**Comment by elsiel23** [comment]
That's right! I'm sorry I missed that when attaching it to the other PR. Will work on that

**Comment by runforyourlives** [comment]
Closed/obsolete, as this refers to an old data model.
