### ISSUE TITLE
Other vector and raster layers for explore

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#22]
Make the following layers available for viewing in the map

- road (geometry) -- tooltip with road name
- slope (raster) -- heatmap, no tooltip or popup. legend needs to be reflective
- buildings (raster) -- 0 or 1 data. dark green color over 1 values
- fire history (geometry) -- popup shows name, acreage, dates, agency, type of fire

**Comment by riecke** [comment]
Min Su to create separate bugs

**Comment by mskim3494** [comment]
Separate bugs created or repurposed
Fire History https://github.com/OurPlanscape/Planscape/issues/447
Buildings https://github.com/OurPlanscape/Planscape/issues/277
Road and slope https://github.com/OurPlanscape/Planscape/issues/276
