### ISSUE TITLE
Backend REST API to query plans in the db

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#256]
The frontend needs 2 APIs to query plans in the database:

- `/plans/userID=<userID>`: returns all the plans (or perhaps partial plans containing a plan ID and display name) for a specific user
- `/plans/planID=<planID>`: returns the full plan schema for a specific plan

Assigning to @riecke for now, feel free to reassign!

**Comment by lattemilk** [comment]
It would also be nice if the createPlan api returned the full created plan so we don't have to call another query for it :)

**Comment by riecke** [comment]
Fixed in https://github.com/OurPlanscape/Planscape/pull/269
