### ISSUE TITLE
Create slope and distance from road layers

### ISSUE THREAD

**Issue by JanLauGe** [OurPlanscape/Planscape#267]
Create rasters with values for slope and distance from road for each cell. Resolution and extent should be identical to the RRK datasets.

**Comment by JanLauGe** [comment]
Update: We're looking to source this layer from Nick instead now.

**Comment by mskim3494** [comment]
Nick has provided the slope raster found [here](https://app.box.com/s/8ehz2mtmzabai5fs4cwj7ot2loz9jgot)
