### ISSUE TITLE
Add BLM (Bureau of Land Management) boundary lines to Explore

### ISSUE THREAD

**Issue by ayee07** [OurPlanscape/Planscape#275]
Requested by Wolfy in UXR interview on 12/27/22

**Comment by thequeenofspades** [comment]
@riecke to delegate to the backend team

**Comment by elsiel23** [comment]
Is this in scope for MVP?

**Comment by riecke** [comment]
See https://github.com/OurPlanscape/Planscape/wiki/How-To#add-a-new-boundary-layer for how to do this.

**Comment by runforyourlives** [comment]
Closed/obsolete
