### ISSUE TITLE
Forsys inputs - Convert US Houses dataset into raster

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#277]
US Houses for California polygon layer is 3.3 GB in size, infeasible to show in the UI.

It's possible we can still show and use the data if turned into a raster, since all we want is to know the presence of buildings.

[Data source](https://github.com/Microsoft/USBuildingFootprints) (search for California).

**Comment by JanLauGe** [comment]
On it!
Can you tell me where I should put it once I'm done? box.com?
@elsiel23 maybe you can chip in as well?

**Comment by elsiel23** [comment]
I think that depends on the purpose of the raster? How is it being used in the tool?

Box is a good place to hold it for now!

**Comment by JanLauGe** [comment]
Output is found in box.com/folder/190464876910 and will be added to the postgresDB by @elsiel23 shortly

**Comment by elsiel23** [comment]
Should we upload the RRK projection ones for now and then upload the newly projected EPSG 3310 rasters post alpha?

**Comment by mskim3494** [comment]
If the uploading does not take much time, I would believe this to be a good idea. My thought is that once we get the updated RRK data we will need to do a large effort to re-upload and re-project rasters, and we can do these in a sprint.

This way we can actually test the implications of having building rasters and their effect on prioritization with actual users before heading into beta.

What do you think?

**Comment by elsiel23** [comment]
@strangeties @JanLauGe would this be a good thing to pick up next sprint?

**Comment by elsiel23** [comment]
Is this layer used for explore only and not forsys?

**Comment by strangeties** [comment]
I don't know whether it'll make forsys beta, but if we complete forsys beta early, then I'd like to incorporate this into forsys (via masking). wdyt?

**Comment by runforyourlives** [comment]
Closed/obsolete.
