### ISSUE TITLE
Return extra fields in response for /plan/list_plans_by_owner

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#282]
Per updated UX guidelines, the user should be able to view a table containing their plans that looks something like this:

![image](https://user-images.githubusercontent.com/10444733/210670735-591db471-4d20-46a9-beb2-16024957afa2.png)

We need to return a few extra fields in the response for `GET /plan/list_plans_by_owner/?owner=<user ID>`:
- Creation timestamp
- Region name
- Number of scenarios
- Status (unclear about this one, seems to be size?)

**Comment by thequeenofspades** [comment]
A couple of small bugs (issues? discrepancies?) I noticed:

- The `region_name` in the response is using the backend name (e.g. `sierra_cascade_inyo`) instead of the display/frontend name (`Sierra Nevada`).
- It would be easier if `creation_time` had a number type instead of a string, so we don't have to convert it twice (string -> unix timestamp -> display string) on the frontend.
- More fields are being returned than necessary (e.g. in the list of plans returned from `GET /plan/list_plans_by_owner`, every field is returned instead of just the ones needed for display in the table). This isn't a problem yet, but could potentially be in the future as plan objects get larger.

**Comment by riecke** [comment]
Good.

1. I'll fix that.
2. Do you want creation_time in "seconds since the epoch" ?  microseconds?  something else?
3. Maybe we should get rid of "geometry" in "/plan/list_plans_by_owner" ?  and leave the rest?  That would be the main size problem, I think.

**Comment by thequeenofspades** [comment]
2. "seconds since the epoch" is what we are using in the frontend for other timestamps, so let's do that.
3. SG!
