### ISSUE TITLE
Remove ability to select "Current condition" or "Current condition (normalized)" in UI

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#297]
We decided not to show "ecosystem" level scores, so we should turn off the following radio buttons in the "Ecosystem scores" section (they currently do nothing):

![image](https://user-images.githubusercontent.com/235727/211211725-4f4cf37e-0f0f-4a3e-bf8c-a64b2b41dd91.png)

**Comment by riecke** [comment]
It's also confusing to select "Current condition" for pillars and elements (they are always normalized).

**Comment by thequeenofspades** [comment]
I can remove the top-level radio buttons for Current condition and Current condition (normalized), but I'm not sure how to represent the fact that pillars and elements are always normalized. @ayee07 do you have any UX input here? I see two options:

- Remove radio buttons from pillars and elements in the Current condition tree (so only metrics are selectable in that tree).
- Leave the radio buttons, but add a warning/note of some kind that pillar/element rasters are always normalized.

**Comment by thequeenofspades** [comment]
On further thought, I'm also curious how/if we should style the radio buttons for pillars/elements if a metric under that pillar/element is selected, but not the whole pillar/element.

**Comment by ayee07** [comment]
Great questions here!
We may want to change the term "Ecosystem scores" to "Ecosystem conditions" 
Then have a selectable "None" (like you already have
And a "Current conditions" (where only metrics under the pillar/element is selectable- Hana's first option)
And a "Opportunity scores" (where all pillars, elements and metrics are selectable)

As for the last question you had, @thequeenofspades  , under Current conditions, only Metrics have radio buttons next to them. And for Opportunity scores, I would need more information for what data we are actually viewing. If the heatmap only accounts for the Metric, then don't select the Element and Pillar. And if the user selects a Pillar, we could disable (grey out) all nested Elements and Metrics. What do you think?

**Comment by riecke** [comment]
Unfortunately, we don't have "Opportunity Scores" yet.  We have neither "current interpreted values" nor "future values", so we can't even compute them.  We won't have them in time for alpha testing either.

Can we call them "Current normalized" as we do now?

**Comment by thequeenofspades** [comment]
@ayee07 `if the user selects a Pillar, we could disable (grey out) all nested Elements and Metrics`

If we disable the nested elements and metrics, it could make it annoying for the user if they want to change their selection to one of the nested elements/metrics. They'd have to select a condition from a different branch of the tree, then go back to the one they actually wanted to select.

We could potentially implement "click a selected radio button to unselect it" though I'm unsure how intuitive that interaction is.

**Comment by ayee07** [comment]
Hana, good point. Maybe we keep the radio buttons next to the disabled elements and metrics. Users can still select one, which unselects that Pillar. I am trying to communicate that by selecting a Pillar, everything under it is considered in the analysis.

**Comment by thequeenofspades** [comment]
`keep the radio buttons next to the disabled elements and metrics` How should we visually indicate that the elements and metrics are disabled?

**Comment by ayee07** [comment]
@riecke @thequeenofspades I am confused with why we would include unstructured conditions (ie. not normalized) scores in the first place. Would "Current metric conditions" as a group title be more clear? And then "Current conditions (normalized) makes more sense

I'm hoping the disabled (greyed out) state would communicate well. 
![Screenshot 2023-01-09 at 2 50 16 PM](https://user-images.githubusercontent.com/101600975/211424018-2959c7fe-51e2-40cc-9f84-bbbaf443fce3.png)

**Comment by riecke** [comment]
I think unstructured (i.e., raw) values for current metrics are called out in the PRD on page 10:

![image](https://user-images.githubusercontent.com/235727/211425562-6d9dacaf-427f-48d2-865b-946ec190a20d.png)

**Comment by thequeenofspades** [comment]
Oh, so style the radio buttons like they're disabled, but they're actually enabled and clickable? Got it, sorry for the confusion.

Here's the plan I've got so far (please correct if anything is wrong):
- For the *un-normalized* condition tree ("Current metric conditions"), remove radio buttons for everything except the leaf nodes (metrics).
- For the *normalized* condition tree ("Current conditions (normalized)"), remove radio buttons for the top-level node ("Current conditions (normalized)"). When a non-leaf node (e.g. pillar or element) is selected, every radio button beneath it should be greyed out, but still selectable.

**Comment by ayee07** [comment]
Yes, I think this will work for Alpha. 
@riecke Got it! We may need to move some categorization within the Map Layer Panel when we have Future projections and Interpreted Values.
