### ISSUE TITLE
"Create scenarios" page in planning flow

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#308]
![image](https://user-images.githubusercontent.com/10444733/211668170-49364227-94ea-4103-ac4e-b56c8f287212.png)

**Comment by thequeenofspades** [comment]
For alpha, the bottom section about opportunity scores isn't needed

**Comment by ayee07** [comment]
![image](https://user-images.githubusercontent.com/101600975/211669014-7872e0ef-a32d-472d-877e-f79176b66124.png)
In the "Create scenarios", "Set priorities", "Set constraints", "Explore & save" screens, the panel can be collapsed (hidden) using the top right tab with an arrow pointing left. By default, the panels are expanded. Users can use the tab to collapse the panel and reveal more of the map. We'll have to add the legend for the map somewhere on the expanded map. TBD...

**Comment by ayee07** [comment]
![image](https://user-images.githubusercontent.com/101600975/211671634-01e42082-1e3b-4740-af21-5ae109ab0337.png)
Example of the panel collapsed
