### ISSUE TITLE
Create a project from scratch

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#31]
User fills out project form manually
Pre-filled info: Acreage, land type, last fire
Manual input: Cost estimation, treatment proposal, collaborators
CTA: Calculate impact score, “Next” (sharing, exporting)

**Comment by thequeenofspades** [comment]
@mskim3494 is creating a project from scratch still in scope for MVP, or can we close this?

**Comment by mskim3494** [comment]
Not in scope, closing
