### ISSUE TITLE
Backend API to get average condition score per metric in a planning area

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#315]
The UX mocks for the "Set priorities" page include color-coded average condition scores and labels per metric for the planning area:

![image](https://user-images.githubusercontent.com/10444733/211942233-60e24d48-8edb-4a65-95c2-52a121324800.png)

The frontend needs to query the backend for these average values. Suggestion for the API: `plan/scores/?plan_id=<ID>` that returns a response like:
```
[
{ "metric_name": <metric1 name>, "avg_score": <metric1 value averaged across planning area> },
{ "metric_name": <metric2 name>, "avg_score": <metric2 value averaged across planning area> },
...
]
```

The frontend can combine this with colormap values to get the color and labels to show.

**Comment by strangeties** [comment]
looking into this now - thanks for making the issue so specific.

**Comment by runforyourlives** [comment]
Closed/obsolete.
