### ISSUE TITLE
Detailed project output

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#33]
View key stats about an area selected
Basic info:

- Owner, other contacts
- Acreage 
- Land type
- Treatment last completed
- Last fire

Impact

- Average treatment score, current condition, future condition
- Key benefits
- Community & population
- Watershed
- Carbon storage
- Old trees

Cost: 

- $$ cost

Treatment type assumption
Risk

- CEQA/NEPA risk
  - Endangered species presence
  - Wetland presence
- Implementation risk
  - slope
  - road access

**Comment by elsiel23** [comment]
@mskim3494 What's the status of this? Is there a mock we should be referring to?

**Comment by mskim3494** [comment]
This feature is outdated and I was going to re-purpose it. Some details on the mocks are still being defined though, ever since the slim down of the beta, so it might need a few more days to settle. Same goes for https://github.com/OurPlanscape/Planscape/issues/34

**Comment by elsiel23** [comment]
See #424
