### ISSUE TITLE
Update Planscape's standard raster projection to use California Teale Albers projection EPSG 3310

### ISSUE THREAD

**Issue by elsiel23** [OurPlanscape/Planscape#333]
The folks who create the RRK raster datasets have decided to use the California Teale Albers projection, EPSG 3310, from here forward for all products including SoCal. 

Post Alpha, we need to:
1. Upload newly projected Sierra Nevada rasters into our database, https://wifire-data.sdsc.edu/nc/s/bNH7NXjEkz5qHSC
2. Update all the raster related constants in Planscape
3. Upload buildings/roads rasters in EPSG 3310 format

**Comment by runforyourlives** [comment]
Closed/obsolete
