### ISSUE TITLE
"Expand Map" on Create Scenarios screen leads to a map without the planning area shown

### ISSUE THREAD

**Issue by mkataria77** [OurPlanscape/Planscape#336]
Adding as high priority from Alpha-readiness discussion w/ Jon, Alex, Min Su on Jan 17.

Description: after drawing a planning area and saving a plan -> go into "create a scenario" screen -> click on "expand map" (screenshot below) -> shows a map but *without* the planning area.

Expected: clicking "expand map" would show a map with the planning area polygon

![image](https://user-images.githubusercontent.com/120220650/213054845-c5db2fdf-afe3-49a8-963d-b571a25854b5.png)

**Comment by ayee07** [comment]
The map should just expand on the default basemap with no layers turned on. 
![image](https://user-images.githubusercontent.com/101600975/213598131-a75ca11d-8a4d-4573-b5ca-1665472086ad.png)

**Comment by mskim3494** [comment]
High priority to disable the "expand map" button for Alpha rollout, with implementation ready for release on the second week .

**Comment by lattemilk** [comment]
Done in https://github.com/OurPlanscape/Planscape/pull/389

**Comment by lattemilk** [comment]
Question for UX and product - when the user clicks "expand map", should they be allowed to edit the planing area in the map view? @ayee07 @mskim3494 @mkataria77

**Comment by mskim3494** [comment]
Synced offline, users cannot edit the planning area once it's created.

**Comment by lattemilk** [comment]
To clarify, this ask is to go back to the "explore map" right? Not just expanding the map. Should the button be renamed to something like "back to map", since it seems to indicate it's just expanding the size of the current map in the planning view?

**Comment by lattemilk** [comment]
Synced in a meeting - this issue is fixed because the tab can expand the map in the planning view. There will be another "expand map" button in the scenario view (see new mocks V4)
