### ISSUE TITLE
In "Set Priorities" screen, enabling a heatmap is super slow

### ISSUE THREAD

**Issue by mkataria77** [OurPlanscape/Planscape#337]
Adding as high priority from Alpha-readiness discussion w/ Jon, Alex, Min Su on Jan 17.

Description & repro steps:

1. Create and save a plan
2. Go into "Create a scenario" flow/screen
3. Click "Next" in bottom right to go to "Set Priorities" screen
4. Enable one of the condition score heatmaps by clicking on the "eyeball" icon. (Screenshot below)

Expected: heatmap of condition score will be rendered quickly or some indication of time remaining will be shown

Seen: map doesn't update for at least 30s. Then slowly starts to update with heatmap.

Jon indicated in the discussion that this flow is using the "old API" and needs to be updated.

![image](https://user-images.githubusercontent.com/120220650/213056387-5d01a558-6b82-404e-b3a3-8e88e56cd404.png)

**Comment by thequeenofspades** [comment]
Fixed by #328
