### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#344]
Some examples:

- alpha[.]planscape[.]org
- planscape-alpha[.]org
- alpha-planscape[.]org

**Comment by mkataria77** [comment]
Got a decision from Patrick Wright (via Nic E) today that they'd like to host the tool on the taskforce site. Nic is following up on more details w/ the taskforce team.

**Comment by mkataria77** [comment]
Still waiting on update from Nic re: tech contact for the task force site. They're also trying to figure out whether to move the static content (everything on planscape.org) at the same time or if that can be done at a separate time.

**Comment by runforyourlives** [comment]
Closing/obsolete.  DNS is managed through Google Domains (err... squarespace) right now
