### ISSUE TITLE
Create separate prod env

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#345]
As we start releasing the tool to users, we need an internal product version to test.

**Comment by elsiel23** [comment]
We currently have 2 DBs, prod and staging. Unit tests and local runs touch the staging instance. 

We have a single set of dev jobs. These jobs touch the prod db instance.

**Comment by runforyourlives** [comment]
Obsolete.  We now have 4 environments (prod, dev, staging, demo), all with separate DBs.
