### ISSUE TITLE
See multiple project proposals on the map

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#35]
View all the projects I have in the pipeline
Show me basic info about my project without going into detail

- name
- acre
- location
- status (shared, private)
- last updated

**Comment by mskim3494** [comment]
Min Su to consider for re-prio, potentially not MVP

**Comment by elsiel23** [comment]
Which screen is this?

**Comment by mskim3494** [comment]
Unsure what the original intent was, but it seems to be something on "My Plans" where you can see the plans on the map and a table type of view. Not a priority for now, we can do just My Plans view instead

**Comment by elsiel23** [comment]
I think this might have been about multiple project proposals in a single plan rather than multiple plans

**Comment by mskim3494** [comment]
I think this one is replaced by https://github.com/OurPlanscape/Planscape/issues/424
