### ISSUE TITLE
Show [min, max] range for raw values

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#351]
Show [min, max] range for raw current condition map layers.

![image](https://user-images.githubusercontent.com/32403265/213233132-379f4f42-7bb4-4880-94eb-6e51fb721345.png)

**Comment by thequeenofspades** [comment]
@riecke or @elsiel23 could we add this to the condition config?

**Comment by riecke** [comment]
It's already there!  For normalized values the min/max is -1, 1.  For current raw metrics, the values are in the config.

Here's what's there as an example.  I'd be nice to put as much as we can fit in it.

             "source": "Sierra Nevada Regional Resource Kit",
                  "source_link": "https://data.fs.usda.gov/geodata/rastergateway/regional-resource-kit/index.php",
                  "data_provider": "USDA Forest Service, Rocky Mountain Research Station",
                  "data_download_link": "https://data.fs.usda.gov/geodata/rastergateway/regional-resource-kit/docs/econDiver.zip",
                  "data_year": "2021",
                  "reference_link": "https://data.fs.usda.gov/geodata/rastergateway/regional-resource-kit/docs/RRK_Metric_Dictionary_v2.pdf#page=30",
                  "min_value": 0,
                  "max_value": 4200

**Comment by thequeenofspades** [comment]
Oh, awesome!
