### ISSUE TITLE
Map layer labels (lower left of each map) not showing proper layer info

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#352]
Went from 2 map to 4 map view, turned on some layers, and map labels were not displaying correctly.

I'm hovering on the Map 3 label, I can see the tooltip showing the layers on it but not the actual label.

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/32403265/213237464-9d0d8170-5a00-4e54-ada1-835110459f74.png">

**Comment by mskim3494** [comment]
Could not reproduce, but Alex also mentioned that sometimes layers that are turned off might still be showing on the label.

**Comment by thequeenofspades** [comment]
Can you describe the exact steps you used to reproduce this? I can't seem to repro by changing from 2- to 4-map view and turning on layers.

**Comment by elsiel23** [comment]
Closed because we're unable to reproduce
