### ISSUE TITLE
Remove blue accessibility box encasing boundaries when selected

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#357]
![image](https://user-images.githubusercontent.com/32403265/213277399-988927e3-557b-4cbe-a8b3-b7042704fd28.png)

**Comment by riecke** [comment]
I've been playing with this, and I think it's a matter of setting some value in CSS.  It's probably related to Leaflet tooltips: when I get rid of the "layer.bindTooltip" call in map-manager.ts, the problem goes away (along with the tooltip).

**Comment by lattemilk** [comment]
Yes I can take a look! Thanks for doing the research on it. Does it work if you put it in the global styles.css file?
