### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#367]
Users may forget their passwords. We need a way for them to recover their accounts through email when that happens.

**Comment by thequeenofspades** [comment]
#3 covers this in part, but we will probably want to break it down into multiple bugs when we get to that point.

**Comment by thequeenofspades** [comment]
Copy-pasting from the latest update on #3:

> To enable email verification and account recovery, the app needs an email backend configured (see Django's documentation [here](https://docs.djangoproject.com/en/4.1/topics/email/)). I've looked into using a Gmail SMTP server and Gmail Planscape account, but it seems no longer feasible due to Gmail's updated security settings ([related Stackoverflow post](https://stackoverflow.com/questions/72794731/set-django-send-mail-backend-host-with-gmail/72794822#72794822)). It's likely you'll need to use a free (with limited usage) mail sending service like Sendgrid instead.
