### ISSUE TITLE
Cannot create a plan when the region is not selected

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#371]
[alpha-planscape_create_plan_as_guest.har.zip](https://github.com/OurPlanscape/Planscape/files/10460500/alpha-planscape_create_plan_as_guest.har.zip)

**Comment by riecke** [comment]
Problem was diagnosed as not having selected a region.  For instance, open an incognito window and go directly to



![Image](https://user-images.githubusercontent.com/235727/213575422-aff7c162-5823-435d-ad02-eb7e071c5665.png)

**Comment by riecke** [comment]
Closing in favor of #375
