### ISSUE TITLE
Forsys: Incorporate stand level constraints into project area ranking

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#388]
Areas such as roads and buildings can't be treated (@mskim3494 which HVRA's should be incorporated?).

They shouldn't be included when computing project area treatment costs, area, etc.

**Comment by strangeties** [comment]
@elsiel23 
@JanLauGe 

Might this data available as either a raster layer or as geometries in the db?

**Comment by elsiel23** [comment]
are HVRAs now limited to roads and buildings? there's #277 and #267 but i'm planning on holding off until we switch to the new raster projection format (EPSG 3310)

**Comment by strangeties** [comment]
Is the format a list of geometries, or a boolean raster?

If it's a list of geometries, I don't think waiting is necessary.

At the same time, its tshirt size is small (or medium at most) so delaying is ok.

**Comment by strangeties** [comment]
(oops - looking at #277 and #267, I see they're rasters)

**Comment by JanLauGe** [comment]
Correct, they are rasters. Buildings is boolean, roads is a "distance layer", meaning that cells with roads have the value 0, all other cells have values >0, increasing with distance from the nearest cell with a road.

**Comment by elsiel23** [comment]
this covers buildings, dist from road, slope

**Comment by runforyourlives** [comment]
obsolete; closing.
