### ISSUE TITLE
Backend: Forsys: Project Area Generation

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#391]
Goal: make a working API for project area generation.

Caveat: it'll probably take a long time to run, and we likely won't have the infrastructure in place to support queries with long run times.

**Realistically, we'll have a working API, but it won't be useable because of run time.**

decision (before starting): should we wait for an optimized forsys project area generation solution, or should we use clustering + the existing forsys project area generation solution?
decision: how can we plan for what will realistically be delivered by alpha phase 4?

**Comment by strangeties** [comment]
@mskim3494 I've updated the description to clarify what will realistically be delivered by alpha phase 4.
How might it affect FE design decisions?

**Comment by elsiel23** [comment]
Testing clustering algorithms to reduce # of stands to speed up patchmax.

Testing with real planning areas from Pete Stine - adjusting constraint values and potentially some new 30x30 rasters

**Comment by elsiel23** [comment]
Generating project areas for set of realistic areas (from Pete Stine)
Feedback: prioritize distance from road 

Clarifying forsys parameter selection with Michelle i.e. secondary constraints, stand/global thresholds. TODO implementing/integrating these params

**Comment by strangeties** [comment]
2 documents:

- [this](https://cawater-my.sharepoint.com/:w:/r/personal/wendy_nie_resources_ca_gov/_layouts/15/Doc.aspx?sourcedoc=%7BA43AA11B-778A-4928-B2D3-AD7DA2B54468%7D&file=Document3.docx) summarizes forsys ranking, generation and provides some context to planscape
- [this](https://docs.google.com/document/d/1NCzQcpjQVxCOz5gkKEN9ejdUpje5zQjbZ2ohvpoGL98/) shows how some parameters affect project area generation (still WIP as I look into #677, #678, #682, #683)

**Comment by strangeties** [comment]
Closing this issue as it's very broad and SIG+Erik may have other thoughts on how to track polishing steps such as selecting reasonable parameters, moving to 30m data, etc.
