### ISSUE TITLE
Tiny UI fix - overflow of text in the conditions drop down menu

### ISSUE THREAD

**Issue by elsiel23** [OurPlanscape/Planscape#396]
Info button shows up on second line (not pictured in screenshot because it's a hover button)
![Screenshot 2023-01-23 at 10 29 40 AM](https://user-images.githubusercontent.com/9139333/214121218-83563d85-6727-41bf-976b-3c8aa7949847.png)

**Comment by thequeenofspades** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/10444733/221718171-ab4855ae-eacd-4ed2-935d-3c898820cc9b.png)
