### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by mkataria77** [OurPlanscape/Planscape#398]
The current demo on AWS seems to only support HTTP, including for the login flows.  Per chat w/ Jon, we should track this TODO to get a cert and enable SSL. It's probably also a pre-requisite for the security assessment / scan that will be performed by the "Agency Security Operations Center" before the site can launch fully.

**Comment by runforyourlives** [comment]
Obsolete; our regular environments, including prod, all run only on HTTPS, and HTTP traffic gets redirected as HTTPS.
