### ISSUE TITLE
Upload federally recognized tribal lands

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#410]
First investigate the differences between the two sources:

- From CARB [link](https://app.box.com/folder/191644207779)
  - "One is the greater extent of Reservations and Rancherias. The second is the track level ownership of tribal people within the Reservations and Rancherias. Lots of non-tribal folks own land within these areas, and the track level data parses that out." -- it's possible it contains the same information as the BIA's, or more detailed. To investigate.
- From Bureau of Indian Affairs (BIA) [link](https://biamaps.doi.gov/bogs/datadownload.html)

**Comment by runforyourlives** [comment]
obsolete; closing.
