### ISSUE TITLE
Get the average of a score in a drawn polygon

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#413]
Alternative to #411: instead of getting the value of a pixel, get the average score in a drawn polygon.

**Comment by ayee07** [comment]
Behavior: After a user draws a closed polygon or uploads a shapefile to show up on the Explore map, they can click on each polygon and see the following information:

- # of acres
- Ownership types: Federal, State, Public, Private, Tribal
- County
- Average of a score (dependent on what heatmap is active on that map)

If Map 1 shows "Score 1", and Map 2 shows "Score 2", after clicking on a drawn/uploaded polygon, I will see the average score of Score 1 from the Map 1 view, and Score 2 from the Map 2 view. I'll have to click on the polygon appearing in each map to see a score specific popup.

**Comment by elsiel23** [comment]
@mskim3494 can you update this for SIG handover?

**Comment by mskim3494** [comment]
There's no mocks, but the design of the popup should be consistent with what's being used for existing project areas, and the expected functionality is detailed above.

**Comment by runforyourlives** [comment]
obsolete; closing.
