### ISSUE TITLE
Rework Explore sidebar

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#415]
From Nick P.: I think there should be some padding beneath the "Ecosystem Scores" in the table of contents (sidebar); the collapsible menu kinda gets lost. I also think I'd put Landtypes - HVRAS in their own collapsible menu together. Those shouldn't be equal to the level of the data and scores in the hierarchy.

![Image](https://user-images.githubusercontent.com/235727/214434139-a8ae694c-f115-443e-a245-63b7d4ef4a04.png)

Suggestion:
1. Remove Land Types and HVRAs for now
2. Change "Ecosystem Scores" to "Data Layers"

**Comment by ayee07** [comment]
![Screenshot 2023-01-24 at 3 36 10 PM](https://user-images.githubusercontent.com/101600975/214444810-531b8936-316f-43c8-8f3a-64d8c8cf13ab.png)

I moved the "coming soon" ones to the bottom of the list. and the attachments defines the margins between elements

**Comment by thequeenofspades** [comment]
These are superseded by latest mocks for the explore sidebar (see Figma)
