### ISSUE TITLE
Ensure mean condition scores are recomputed every time a planning area is changed (or added)

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#431]

**Comment by elsiel23** [comment]
Does this still make sense in our user flow?

**Comment by strangeties** [comment]
Perhaps not.

Upon a condition score request, planscape first tries to look up the scores in the db, then computes them if they're unavailable.

I assume in the FE, a save request is automatically followed by a condition score request?

**Comment by runforyourlives** [comment]
obsolete; closing.
