### ISSUE TITLE
Zoom set to max when planning

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#454]
When opening the plan details to set priorities and constraints, the map is set to max zoom. Depending on the size of the planning area it can take 10+ zoom outs to see the whole area. 

![image](https://user-images.githubusercontent.com/32403265/215798779-91d3f9d8-508e-4f73-936b-a9433ba85e98.png)

Ideally, default to a zoom level that shows the entire planning area when collapsing the stepper

![image](https://user-images.githubusercontent.com/32403265/215799011-9cace5d0-1c2c-4612-87ae-915a3db916d7.png)

**Comment by thequeenofspades** [comment]
Could you provide a plan ID where I can repro this bug? I can't repro it in any of the random plans I tried opening in the planning view.

**Comment by mskim3494** [comment]
It's disappeared after the new release.
