### ISSUE TITLE
Migrate staging data folder from Box account to more permanent solution

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#457]
Currently we use on developer's personal Box account.  We need to find a location that is managed by the org, not by an individual.
Possible solution is S3.

**Comment by elsiel23** [comment]
@runforyourlives to follow up with SIG folks

**Comment by elsiel23** [comment]
Load to SIG's Google Drive

**Comment by runforyourlives** [comment]
Obsolete; tracked elsewhere
