### ISSUE TITLE
Backend API: get scenario objects for a plan

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#463]
We need a backend API to get the scenarios for a plan so we can show them in the Plan Overview. Something like `/plan/get_scenarios/?planId=<ID>` that returns a list of scenario objects.

**Comment by elsiel23** [comment]
Are you blocked on /create_scenario? I can add that too

**Comment by lattemilk** [comment]
I think either an api to query scenarios by plan ID or just include them in the get_plan API (instead of number of scenarios)?

**Comment by elsiel23** [comment]
thanks for calling those out! we don't have any scenario data there yet, but i'll add it once that becomes available (or as we get closer)

**Comment by runforyourlives** [comment]
Obsolete, but we do have an API to fetch a plan's scenarios.
