### ISSUE TITLE
UX: define theme palette

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#465]
Until now, we've been using the Material grey palette (https://material.io/design/color/) for the Planscape frontend. The mocks have certain UI elements (buttons, etc.) in various shades of blue, but these don't correspond to the Material 2014 blue palette. If we want to have a custom palette, it would be extremely helpful to have all the colors in the application defined somewhere.

**Comment by runforyourlives** [comment]
closed; obsolete
