### ISSUE TITLE
Frontend: Add completed state to steps in plan stepper

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#468]
Each of #419 , #420 , #421 , #423 , and #424 have a "completed" state that shows a summary of the inputs chosen. This isn't a built-in feature of the Stepper component, so we'll have to build something custom.

Example (steps 1-3 are completed)
![image](https://user-images.githubusercontent.com/10444733/216435928-cbbe12f9-f677-4b74-a891-e75e5e9d8c34.png)

**Comment by runforyourlives** [comment]
closed; obsolete
