### ISSUE TITLE
Tool orientation

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#47]
Quick orientation in-tool tutorial
How do I use this tool?

**Comment by mskim3494** [comment]
[The user guide](https://github.com/OurPlanscape/Planscape/wiki/Planscape-User-Guide) should be linked to the tool. for MVP, there needs to be a question mark icon at the top bar with a link to the user guide.

**Comment by runforyourlives** [comment]
Closedobsolete.
