### ISSUE TITLE
Documentation: update wiki with backend APIs

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#473]
Please update https://github.com/OurPlanscape/Planscape/wiki/Backend-API with the `/plan/update_project` API and any other APIs currently lacking documentation. Thanks!

**Comment by elsiel23** [comment]
@strangeties I added a section for get_scores in https://github.com/OurPlanscape/Planscape/wiki/Backend-API#planscape-backendplanget_scores. Let me know if that sounds right!

**Comment by runforyourlives** [comment]
closed; obsolete
