### ISSUE TITLE
Forsys inputs - load road proximity rasters into database

### ISSUE THREAD

**Issue by elsiel23** [OurPlanscape/Planscape#476]
To be retrieved for a forsys constraint. Used to restrict pixels before forsys is called.

box.com/folder/190464876910

**Comment by strangeties** [comment]
Hoping to get a sense of how to prioritize:
- Is there a deadline?
- And will the data also be available as a layer to be shown to users?

**Comment by strangeties** [comment]
@mskim3494 (for a product perspective)

**Comment by mskim3494** [comment]
- Road proximity -- only for the backend ForSys calls.
- Slope -- used for both ForSys and FE explore

Deadline is beta launch from a product perspective. Technically, certain features on the ForSys calls (exclusion based on slope and road proximity) are dependent on having these layers, so really whenever it becomes a blocker for further ForSys + FE development.

**Comment by strangeties** [comment]
done for 300m data.
