### ISSUE TITLE
Forsys inputs - load buildings rasters into database

### ISSUE THREAD

**Issue by elsiel23** [OurPlanscape/Planscape#477]
To be retrieved for a forsys constraint. Used to restrict pixels before forsys is called.

box.com/folder/190464876910

**Comment by strangeties** [comment]
Hoping to get a sense of how to prioritize:
- Is there a deadline?
- And will the data also be available as a layer to be shown to users?

**Comment by strangeties** [comment]
@mskim3494 (for a product perspective)
