### ISSUE TITLE
Get user's first name, last name, department using userId

### ISSUE THREAD

**Issue by lattemilk** [OurPlanscape/Planscape#483]

**Comment by ayee07** [comment]
While a user is registering, should we ask for these fields? How does one make sure it's valid?

**Comment by lattemilk** [comment]
The only way to get this info is to have the users provide it. Will need to add user inputs to the UI and save the fields through the backend. We can do checks for validating simple input stuff like length or special characters, but as for actually verifying if it's accurate? I don't think that's possible unless there's some api out there that allows us to check their department/names.

**Comment by runforyourlives** [comment]
closed; obsolete
