### ISSUE TITLE
Alpha: Frontend: Usability Feedback -  Map layers difficult to parse visually

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#498]
We have received consistent feedback that the map layers in explore are difficult to parse and the selected layer affordance isn't visible enough. Leveraging the angular system an updated design proposal has been added to the Figma file page - Map Legend & Layers Updates. 

![image](https://user-images.githubusercontent.com/125076521/218157170-313e7c93-b44c-4c50-9549-ef15cb123656.png)

**Comment by thequeenofspades** [comment]
Remaining work here:

- Add the blue background to the selected item
- Shift the info icon all the way to the right of the box
- Add the blue dot to the left of all ancestors of a selected item
- Add borders to items
- Add shading to Tier 2 items
