### ISSUE TITLE
Alpha: Frontend: Usability Feedback - 'i' affordance and 'i' overlay for map layers

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#499]
User feedback per the 'i' overlay once the 'i' is pressed in the map layers is that the information is to sparse to be useful. Additional feedback is that the 'i' icons are always visible versus current implementation where the 'i' affordance is only visible on rollover.

Updated design proposal / interaction model in Figma page - Map Legend & Layers Updates.

![image](https://user-images.githubusercontent.com/125076521/218159661-d6cf179b-4122-4545-8eb8-19ef7985bf9e.png)

**Comment by thequeenofspades** [comment]
The remaining work here is to make the extra data available in the backend condition config:
- Metric definition and relevance
- Data resolution
- Data units

Assigning to @mskim3494 for now to figure out where to source this data. Once we know that, an engineer can add them to the config.

**Comment by mskim3494** [comment]
@thequeenofspades - you can find data units in the config now https://github.com/OurPlanscape/Planscape/blob/main/src/planscape/config/conditions.json#L32

We'll try to hold off on data resolution for now, as it may or may not have to change with 30m data

**Comment by thequeenofspades** [comment]
Opened #634 to track adding metric definition and relevance, which is the only remaining work for this bug.
