### ISSUE TITLE
Alpha: Frontend: Usability Feedback - Top Menu buttons for drawing environment unclear to alpha testers

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#500]
Alpha testers noted having a difficult time noticing the "done" button in upper left while in drawing environment to complete their area drawing.

Proposed updates to buttons to trigger drawing environment OR upload shape file in Figma file page - Drawing Tool Updates. 

Additionally buttons are updated to raised button style vs FAB.

![image](https://user-images.githubusercontent.com/125076521/218160438-4015401c-09e5-49cb-93a4-749e3ef83f4a.png)

**Comment by ayee07** [comment]
For more clarification, the "Create a plan" button should be blue by default. 
![Screenshot 2023-02-13 at 3 24 48 PM](https://user-images.githubusercontent.com/101600975/218596970-ba69193d-984b-42a6-9b64-7c2e1a055b75.png)

When users click on "Create a plan", it should reveal the "Draw Area" and "Upload Area" options in white (w/blue text) & enabled states. The Cancel and Done buttons should appear to the right of the screen with updated button styles to stand out more.
When users click on either "Draw Area" or "Upload Area", the selected button turns to Blue button/white text style, and the other options turn into disabled state.

**Comment by ayee07** [comment]
![Screenshot 2023-02-13 at 3 29 44 PM](https://user-images.githubusercontent.com/101600975/218597670-8df5b15b-46ca-462c-9bde-f83fdb45878a.png)

**Comment by ayee07** [comment]
![Screenshot 2023-02-28 at 3 26 39 PM](https://user-images.githubusercontent.com/101600975/222006303-ca59b982-0ce0-4fdc-9190-16eae9a939c8.png)
I got rid of the first button. no need to have that collapsed button step. Let's show both the Draw and Upload buttons always
