### ISSUE TITLE
Alpha: Frontend: Usability Feedback - Update to color of area shape overlay on map

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#501]
Alpha user feedback that the current purple color palette used for the area shape definition on the map was not usable and competed with heat map colors.

Updated proposal to use generic blue highlight color #3367D6 with 10% opacity and increase stroke thickness to 8 pixels.

Design proposal in Figma file under Drawing Tool Updates page.

**Comment by lattemilk** [comment]
Do you also want this change in the Plan view map?
