### ISSUE TITLE
Switch map layers to normalized conditions in Plan stage

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#514]
Currently heatmaps in the "Select Priorities" view are raw values, should be normalized conditions. Switch to normalized conditions

![image](https://user-images.githubusercontent.com/32403265/218565731-a4200521-6675-454d-bd9d-c29935056f8f.png)

**Comment by ayee07** [comment]
Also, the qualitative ranges showing under the Conditions score column should follow the PRD:
For normalized value heatmaps, categorical divisions are shown on the legend, ranging as follows: 

(-1, -0.7) Poor   
(-0.6, -0.3) Fair  
(-0.2, 0.2) Ok 
(0.3, 0.6) Good 
(0.7, 1) Excellent 

The legend needs to be updated to this:
![Screenshot 2023-02-13 at 3 20 46 PM](https://user-images.githubusercontent.com/101600975/218596487-55facbee-0ef6-4965-9a0e-c5268398eb4e.png)
https://screenshot.googleplex.com/Aw4f8YBAiJxmnEm

![Screenshot 2023-02-13 at 3 21 43 PM](https://user-images.githubusercontent.com/101600975/218596586-67463359-e297-47d1-a105-b652de158850.png)
When a user clicks on the 'i' icon, show a pop up with the condition score range categories
