### ISSUE TITLE
Add Saved Scenarios Details page

### ISSUE THREAD

**Issue by lattemilk** [OurPlanscape/Planscape#515]

**Comment by lattemilk** [comment]
Finished:
fill in details panel:
  [x] planning area details
  [x] configuration
  [x] notes
[x] share plan and get scenario data via service to components
[x] add overall structure of scenario details
[x] share plan map and navigation bar
[x] modify plan-navigation-bar to go back to plan overview route
[x] make collapsible panel reusable
[x] set up barebones scenario details view
[x] setup routing to scenario details page

Splitting remaining todos into:
https://github.com/OurPlanscape/Planscape/issues/585
https://github.com/OurPlanscape/Planscape/issues/586
https://github.com/OurPlanscape/Planscape/issues/587

**Comment by runforyourlives** [comment]
closed; obsolete
