### ISSUE TITLE
"Clear all" button for maps

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#517]
Button that removes all layers for the selected map

**Comment by Moon1388** [comment]
Proposal is to have the button appear at the top of the map palette. Default will be the inactive state, and any boundaries or  layers on the map are toggled on it will appear in the "up" state (blue). 

Pressing the Clear All button will select "all layers off" radio button in the Ecosystem Scores Section, as well as select the "none" radio button in the Boundary section and uncheck existing projects.

Proposal in Figma file page - Map Legend & Layers Updates.

Screenshot:
<img width="1634" alt="Screenshot 2023-02-17 at 1 34 16 PM" src="https://user-images.githubusercontent.com/125076521/219801602-612bb01a-8810-4875-bb7d-67f37d4d95a5.png">
