### ISSUE TITLE
Treatment score

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#52]
What’s included in the treatment score? 
How is the score calculated?

**Comment by mskim3494** [comment]
There should be a small explanation in the tool where the score is coming from. There should be a link that sends the user to a section within the help center / wiki user guide that explains it for non-technical users, which also links to the Rmd file that shows the technical derivation

**Comment by runforyourlives** [comment]
Closed/obsolete, although the need to display where data came from is a constant ask.
