### ISSUE TITLE
Area Overview- Open a Config or Scenario by clicking on a table row

### ISSUE THREAD

**Issue by ayee07** [OurPlanscape/Planscape#524]
Currently you have to select the checkbox then click "See details" or "Continue planning", but to make it easier for the user to open a Config or Scenario item in the tables, we want to change the behavior to the following:
When a user is hovering over a table row, highlight it in blue. When a user clicks anywhere within that row, it'll open that item (config or scenario). You can only open one item at a time, ie the "Continue Planning" button is only enabled when one row is selected in the Configuration table. If user selects another row with the checkbox, the button becomes disabled. But if the user hovers over a row item, they can still click within that row to open that item.
![image](https://user-images.githubusercontent.com/101600975/218607991-bca92a73-665b-4060-97c9-bb1ee054f35f.png)

A user can delete configs or scenarios by selecting a checkbox then clicking "DELETE"

Deleting rules:
You can only delete your own Configurations and Saved Scenarios.

**Comment by thequeenofspades** [comment]
Remaining work here:
- Highlight hovered rows in blue.
- Add select box and delete button for scenarios. (It's already there for configurations.)
