### ISSUE TITLE
Error in `plan/update_project` API

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#532]
Encountered an error when trying to save the `structure_exposure` metric as a priority in a project config (the same error doesn't occur when I only try to save `carbon_sequestration`, or `carbon_sequestration` plus another pillar, so it might be an issue with metrics).

![image](https://user-images.githubusercontent.com/10444733/218878611-4fcea08a-49af-48e0-9f13-3ddbb86540ff.png)

![image](https://user-images.githubusercontent.com/10444733/218878529-ba1dc230-b19c-4b6a-a2da-d28c89699c99.png)
![image](https://user-images.githubusercontent.com/10444733/218878563-6745d4e5-f2f0-4847-9735-4be1fd08bcb0.png)

**Comment by elsiel23** [comment]
Fixed by #546
