### ISSUE TITLE
Treatment & cost assumptions

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#54]
View assumptions made about the costs and treatment types

**Comment by mskim3494** [comment]
Need a question mark popup when putting estimated constraint cost per acre, explaining that max budget and estimated cost per project area and planning areas will be based on such number. In its absence, max budget constraining is not available, and neither are estimated costs per project and planning areas.

**Comment by runforyourlives** [comment]
Closed/obsolete, although the new scenario UI should have ideally enough clues to the users about each option.
