### ISSUE TITLE
refresh endpoint causing error

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#545]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/32403265/219468313-282c95c4-ab20-4afe-bb2f-747b33c37b0b.png">

<img width="545" alt="image" src="https://user-images.githubusercontent.com/32403265/219468583-1c9f214f-e025-4123-90e4-4ae68d2b9a69.png">

**Comment by thequeenofspades** [comment]
This is working as intended; the app attempts to refresh the user login token on load, and if the token isn't valid, the request fails (and the user stays logged out). There isn't any way to prevent the error from appearing in the Chrome console, but it's not actually causing any issues.
