### ISSUE TITLE
Update to drawing tool buttons 

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#575]
Update to interaction for drawing tool buttons. We eliminated the "create a plan" button that triggers open "Draw an Area" and "Upload an Area". Updated proposal in Figma file on Drawing Tool Updates page.

Dupe of Issue #500 

(Full design and interaction proposal in Figma file - screenshot attached for example only.)

<img width="1541" alt="Screenshot 2023-02-24 at 1 27 14 PM" src="https://user-images.githubusercontent.com/125076521/221296381-f9b39387-5239-4bde-a0a1-7b7550b83e3e.png">

**Comment by runforyourlives** [comment]
closed; obsolete
