### ISSUE TITLE
UX Strings : Updated strings for Sign in page

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#615]
See attached image for copy updates for the sign in page. Also located in Figma file page UXW-Strings.

![image](https://user-images.githubusercontent.com/125076521/222849897-77fb34ee-caee-4148-837c-35eae5bc1c83.png)

**Comment by ayee07** [comment]
![image](https://user-images.githubusercontent.com/101600975/223302208-7da08ee6-b3ec-4c8e-b22e-3a9c41eccddd.png)
Please use this one instead. (forgot to update a few strings in the original image)
