### ISSUE TITLE
UX Strings : Updated copy for global navigation

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#618]
See attached image for copy updates for the global navigation. Also located in Figma file page UXW-Strings.

![image](https://user-images.githubusercontent.com/125076521/222852264-ae048744-2a4d-4ed3-a340-424f8dfd13c8.png)

**Comment by ayee07** [comment]
if the user is already signed in, the "Sign in / Create account" should say "Log out"
