### ISSUE TITLE
UX Strings : Updated copy for layer performance in map layer palette AND Map performance dialogue link.

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#619]
Additional strings in may layer palette "Layers may take a moment to show on the map" and a dialogue when user clicks "Improve Map Performance" 

![image](https://user-images.githubusercontent.com/125076521/222852523-054b0499-d20b-4974-8ac9-be20dab7b99f.png)

**Comment by runforyourlives** [comment]
closed; obsolete
