### ISSUE TITLE
UX Strings : String updates to master stepper module

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#623]
String updates to master stepper module. Located in Figma file page UXW - Strings

Some font style changes to Adjust weights section (roboto medium 12pt and roboto semi-bold 20pt)

![image](https://user-images.githubusercontent.com/125076521/222853906-7739300e-d414-4971-8d7e-dd09b76e5934.png)

**Comment by runforyourlives** [comment]
closed; obsolete
