### ISSUE TITLE
UX Strings : Plan Summary states string updates.

### ISSUE THREAD

**Issue by Moon1388** [OurPlanscape/Planscape#625]
See attached PNGs and refer to Figma file page UXW-Strings for string updates and different states. 

![image](https://user-images.githubusercontent.com/125076521/222854682-799cd031-08ca-4fe3-9cb9-994fca8e91b2.png)

![image](https://user-images.githubusercontent.com/125076521/222854480-6f2f9e0b-524d-4084-a94a-5df544b9aa42.png)

![image](https://user-images.githubusercontent.com/125076521/222854508-21191feb-a42e-4c5c-baae-8f9226a1b44c.png)

**Comment by runforyourlives** [comment]
closed; obsolete
