### ISSUE TITLE
Sensitivity analysis and trade-off decision on `sample_frac`

### ISSUE THREAD

**Issue by JanLauGe** [OurPlanscape/Planscape#641]
Forsys and Patchmax use `patchmax_sample_frac` to determine the number of cells that should be sampled to "grow" project areas from. A very low value for `saple_frac` will result in project areas that are probably not ideal, because the best solution has not been found. A very high value will result in a very long run time (O(n)).

We should test different values of `sample_frac` on realistic project areas to make sure we're using a value in the sweet spot.

**Comment by runforyourlives** [comment]
closed; obsolete
