### ISSUE TITLE
refreshing takes you back to previous selections

### ISSUE THREAD

**Issue by joncross1** [OurPlanscape/Planscape#654]
#When I undo / clear data selections in the Explore workflow, and then refresh the page (sometimes I do this if the tool is slow, or the map's not loading) it jumps back to my previous selections, meaning I have to undo them again.

**Comment by thequeenofspades** [comment]
This happens because we save to the local cache every 60 seconds, not constantly or whenever a change is made. Leaving this open in case we want to revisit that decision, as discussed in chat.

**Comment by runforyourlives** [comment]
closed; obsolete
