### ISSUE TITLE
Restrict access to backend APIs for signed out (Guest) users

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#658]
All POST/PATCH/DELETE endpoints should be restricted to signed in users.

Any GET endpoint that looks up data associated with a user (get plans, get scenarios, etc.) should be restricted to signed in users.

These calls should all throw 403 Forbidden errors if the user isn't signed in.

**Comment by runforyourlives** [comment]
Obsolete, although all plan/scenario endpoints require a logged in user.
