### ISSUE TITLE
Expand Priorities list (all the way to Metrics) to show previous selected priorities in an existing configuration

### ISSUE THREAD

**Issue by ayee07** [OurPlanscape/Planscape#664]
When i open a configuration that I've already selected priorities for (in a previous session), I see this:
![Screenshot 2023-03-14 at 6 02 36 PM](https://user-images.githubusercontent.com/101600975/225177606-97fc3113-36dd-42df-89f3-b210739bb500.png)
Which makes it look like I didn't select any priorities. 
Can we show the page with all the metrics expanded out in the list? Like this: 
![Screenshot 2023-03-14 at 6 04 10 PM](https://user-images.githubusercontent.com/101600975/225177764-1f28d3c0-e013-4cb3-9b9d-0215344b19fe.png)
That way I can scroll and i'll see the things I've selected more easily
![Screenshot 2023-03-14 at 6 03 11 PM](https://user-images.githubusercontent.com/101600975/225177828-5b423f1d-7548-47f5-b78e-8439996bc0a7.png)

**Comment by runforyourlives** [comment]
closed; obsolete
