### ISSUE TITLE
Not seeing the Scenarios Cynthia created in Goddess Plan

### ISSUE THREAD

**Issue by ayee07** [OurPlanscape/Planscape#667]
This is what I see when I open the Goddess page
I think I'm supposed to be able to see a scenario that Cynthia made
![Screenshot 2023-03-14 at 6 13 34 PM](https://user-images.githubusercontent.com/101600975/225178881-1cdfa911-aff0-4725-a5d6-fa098216402d.png)

**Comment by elsiel23** [comment]
how long ago was the scenario created? we cleared some objects in the table recently. i verified that we have no scenarios with plan_id=51 in our db so the FE is WAI

**Comment by lattemilk** [comment]
Is the demo version of Planscape using prod db? My test scenario for plan 51 is in the dev db.

**Comment by elsiel23** [comment]
It's using the prod db, sounds like this isn't a bug!

**Comment by elsiel23** [comment]
Which latest changes are you referring to? We pushed this AM, so anything cut before that point is pushed to prod

What is the expected behavior you were trying to verify?

**Comment by ayee07** [comment]
I was just trying to see things that Cynthia and Hana already fixed. This one thing I was trying to see in particular were scenarios that Cynthia created within the Goddess plan. I just took this screenshot:
![Screenshot 2023-03-16 at 9 59 09 AM](https://user-images.githubusercontent.com/101600975/225695924-ccad979a-0093-4a23-8d81-41ff60483a6d.png)
@lattemilk is there supposed to be anything in the Scenarios section?

**Comment by elsiel23** [comment]
There should not be anything in the Scenarios section for this plan. I verified that we have no scenarios with plan_id=51 in our prod db.

**Comment by ayee07** [comment]
ok sounds like all is WAI
