### ISSUE TITLE
Select reasonable parameters for EPW, exclusion_limit, project area size constraints for 30m x 30m AP impact data

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#678]
This is dependent on #675, #476, #679, #680 (and possibly also https://github.com/OurPlanscape/Planscape/issues/481 and https://github.com/OurPlanscape/Planscape/issues/676).

It will require experimentation and documentation.

**Comment by runforyourlives** [comment]
closed; obsolete
