### ISSUE TITLE
Update ForsysRankingRequestParamsFromDb and ForsysGenerationRequestParamsFromDb

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#681]
Update request params to read config parameters from db.

**Comment by strangeties** [comment]
Update:
also wrote generation output to DB.
@runforyourlives is working on reading constraints (e.g. max cost, max acreage) from DB - that can be a separate issue.

**Comment by runforyourlives** [comment]
closed; obsolete
