### ISSUE TITLE
Project area generation stopping criteria

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#689]
Presently, a project area is "complete" when it hits one either max-project-area-acreage or max-project-area-cost.

Is it possible to decide a project area is "complete" based on how its total impact score changes as a function of area? e.g. based on the area-weighted mean impact of the latest X stands that were added.

This could potentially result in more variable project area sizes.

This takes inspiration from ...
1) how ML training repetitions stop based on how estimation error changes over time
2) how project areas have a minimum acreage, but no maximum acreage

This would involve some collaboration with Michelle, Cody, and the Forsys team - definitely not a short-term task.

**Comment by runforyourlives** [comment]
closed; obsolete
