### ISSUE TITLE
Map layers - create accessible colors for heatmaps

### ISSUE THREAD

**Issue by JanLauGe** [OurPlanscape/Planscape#71]
Create color schemas that are accessible, user friendly, and intuitive. Apply them to the different map data layers we will want to visualize in the tool frontend. Requires collaboration across Eng / Product / UXR!

**Comment by thequeenofspades** [comment]
https://github.com/wistia/heatmap-palette <--- potential place to start?

**Comment by riecke** [comment]
That does look like a good place to start.  Hana, do you think we should create and use several fixed color schemes for heatmaps, with the frontend making a choice through the API?  The WMS protocol allows one to send a comma-separated list of styles---we could make the backend understand a few.

**Comment by JanLauGe** [comment]
To add an option, there are the [viridis color scales](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) that I mentioned before.

We probably need multiple scales, I propose to try to use semantic color scales where possible (e.g. bright red or amber = high fire risk, light green = high forest resilience)

**Comment by riecke** [comment]
Out-of-scope to choose between different color schemes

**Comment by thequeenofspades** [comment]
Just for future reference, I think the steps needed here are:
- create and use several fixed color schemas for heatmaps
- create a param in the API to specify which color schema should be used
- hardcode the param in the frontend request to backend
- update the legends in frontend with the color codes being used
