### ISSUE TITLE
Update "Clear All" string to "Clear all layers"

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#753]
Preliminary testing suggests users may expect the button to clear all 4 maps. Update the string to make it clearer to the user that it's for the specific map in focus.

![image](https://user-images.githubusercontent.com/32403265/228371919-83f4f879-0417-4a1b-a0cd-233298ea1431.png)

**Comment by runforyourlives** [comment]
Closed; obsolete
