### ISSUE TITLE
[optional] Incorporate logic for filtering by buildings, road proximity, and slope into project area ranking

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#756]
For ranking, a user provides project areas that are scored according to formula, 
Project area score = weight(c1) * impact(c1) + weight(c2) * impact(c2) + … + weight(ci) * impact(ci) 

The impact of a project area is the sum of the impact of all the stands in a project area.

Should project area impact scores be affected by attributes such as buildings, road proximity, and slope?

If not, this issue can be obsolete.

If so, decisions need to be made about how the project area impact scores are affected. One option: impact of project area stands that occupy buildings are not included in the project area impact sum.

**Comment by runforyourlives** [comment]
closed; obsolete
