### ISSUE TITLE
Read/write to DB.

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#757]
Project area ranking runs, but results are not written to DB.

One task involves 1) ensuring ranking parameters are read properly from DB (the logic may be out of date since the last model change) and 2) writing results to DB.

Reference classes and functions include ForsysGenerationRequestParamsFromDb and save_generation_output_to_db.

**Comment by runforyourlives** [comment]
This is obsolete as we've changed the way project areas are generated; storage is already happening.
