### ISSUE TITLE
Make Forsys return fewer than n project areas if there aren't enough stands to generate n project areas 

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#760]
The number of project areas generated by Patchmax is specified by patchmax_proj_number.

If patchmax_proj_number=3 and only 2 project areas can be generated from the provided stands, Forsys issues a failure.

Instead, we want Forsys to stop and return the 2 generated project areas.

This will require changes to the forsys library (https://github.com/forsys-sp/forsysr/issues/111).

**Comment by runforyourlives** [comment]
closed; obsolete
