### ISSUE TITLE
Not offered an option to login when logged out

### ISSUE THREAD

**Issue by lankyrob** [OurPlanscape/Planscape#772]
I'm only offered "Create an account" and when I click the avatar icon top right it just says 'welcome guest" 

If I follow the create an account link I can eventually find a login option, but I think it should be presented earlier

<img width="1486" alt="Screenshot 2023-04-14 at 4 21 31 PM" src="https://user-images.githubusercontent.com/1701257/232147909-67290ec7-bc27-4f9c-9b37-421af1547c17.png">
<img width="1489" alt="Screenshot 2023-04-14 at 4 24 57 PM" src="https://user-images.githubusercontent.com/1701257/232147997-91271872-5f4d-413a-bf96-f739af35afe3.png">

**Comment by runforyourlives** [comment]
This has been fixed now (visible when we launch login).

![Screenshot 2023-09-13 at 2 39 24 PM](https://github.com/OurPlanscape/Planscape/assets/125416076/d5e43569-64b2-42ae-9f38-a1aef591100d)
