### ISSUE TITLE
Prototype multimap view & estimate eng cost

### ISSUE THREAD

**Issue by thequeenofspades** [OurPlanscape/Planscape#93]

**Comment by thequeenofspades** [comment]
https://github.com/jieter/Leaflet.Sync <---- this looks promising! I'm going to try it out

**Comment by lattemilk** [comment]
Here are some of tasks we'd need to do for the multimap version:
1. implement syncing of map when panning/zooming <-- solved by your prototype
2. mirror polygon drawings in all maps
3. save where user left off for the multimap view
4. have legend change according to selected map
5. be able to select current map
6. be able to toggle map view, build UI component
7. display descriptions on the bottom for each map

anything else you can think of?

**Comment by thequeenofspades** [comment]
That list looks good to me! Maybe we can add more items once we have the single-map mocks from Alex and Shawn to compare with.

**Comment by riecke** [comment]
Is this done?  Should we add bugs for any individual items remaining?

**Comment by thequeenofspades** [comment]
Done items: 1, 5, 6, 7
Not done items: 2, 3, 4

Yes, we can add bugs for individual items and close this one. I'll do that after sprint planning today.

**Comment by thequeenofspades** [comment]
2 is covered by #139 

Opened #152 for 3

4 is covered by #71 

Closing now. Thanks!
